const data = {};

data.prompts = {};

data.prompts.values = [
    "Acceptance",
    "Accomplishment",
    "Accountability",
    "Accuracy",
    "Achievement",
    "Adaptability",
    "Alertness",
    "Altruism",
    "Ambition",
    "Amusement",
    "Assertiveness",
    "Attentive",
    "Awareness",
    "Balance",
    "Beauty",
    "Boldness",
    "Bravery",
    "Brilliance",
    "Calm",
    "Candor",
    "Capable",
    "Careful",
    "Certainty",
    "Challenge",
    "Charity",
    "Cleanliness",
    "Clear",
    "Clever",
    "Comfort",
    "Commitment",
    "Common sense",
    "Communication",
    "Community",
    "Compassion",
    "Competence",
    "Concentration",
    "Confidence",
    "Connection",
    "Consciousness",
    "Consistency",
    "Contentment",
    "Contribution",
    "Control",
    "Conviction",
    "Cooperation",
    "Courage",
    "Courtesy",
    "Creation",
    "Creativity",
    "Credibility",
    "Curiosity",
    "Decisive",
    "Decisiveness",
    "Dedication",
    "Dependability",
    "Determination",
    "Development",
    "Devotion",
    "Dignity",
    "Discipline",
    "Discovery",
    "Drive",
    "Effectiveness",
    "Efficiency",
    "Empathy",
    "Empower",
    "Endurance",
    "Energy",
    "Enjoyment",
    "Enthusiasm",
    "Equality",
    "Ethical",
    "Excellence",
    "Experience",
    "",
    "Exploration",
    "Expressive",
    "Fairness",
    "Family",
    "Famous",
    "Fearless",
    "Feelings",
    "Ferocious",
    "Fidelity",
    "Focus",
    "Foresight",
    "Fortitude",
    "Freedom",
    "Friendship",
    "Fun",
    "Generosity",
    "Genius",
    "Giving",
    "Goodness",
    "Grace",
    "Gratitude",
    "Greatness",
    "Growth",
    "Happiness",
    "Hard work",
    "Harmony",
    "Health",
    "Honesty",
    "Honor",
    "Hope",
    "Humility",
    "Humor",
    "Imagination",
    "Improvement",
    "Independence",
    "Individuality",
    "Innovation",
    "Inquisitive",
    "Insightful",
    "Inspiring",
    "Integrity",
    "Intelligence",
    "Intensity",
    "Intuitive",
    "Joy",
    "Justice",
    "Kindness",
    "Knowledge",
    "Lawful",
    "Leadership",
    "Learning",
    "Liberty",
    "Logic",
    "Love",
    "Loyalty",
    "Mastery",
    "Maturity",
    "Meaning",
    "Moderation",
    "Motivation",
    "Openness",
    "Optimism",
    "Order",
    "Organization",
    "Originality",
    "Passion",
    "Patience",
    "Peace",
    "Performance",
    "Persistence",
    "Playfulness",
    "Poise",
    "Potential",
    "Power",
    "",
    "Present",
    "Productivity",
    "Professionalism",
    "Prosperity",
    "Purpose",
    "Quality",
    "Realistic",
    "Reason",
    "Recognition",
    "Recreation",
    "Reflective",
    "Respect",
    "Responsibility",
    "Restraint",
    "Results-oriented",
    "Reverence",
    "Rigor",
    "Risk",
    "Satisfaction",
    "Security",
    "Self-reliance",
    "Selfless",
    "Sensitivity",
    "Serenity",
    "Service",
    "Sharing",
    "Significance",
    "Silence",
    "Simplicity",
    "Sincerity",
    "Skill",
    "Skillfulness",
    "Smart",
    "Solitude",
    "Spirit",
    "Spirituality",
    "Spontaneous",
    "Stability",
    "Status",
    "Stewardship",
    "Strength",
    "Structure",
    "Success",
    "Support",
    "Surprise",
    "Sustainability",
    "Talent",
    "Teamwork",
    "Temperance",
    "Thankful",
    "Thorough",
    "Thoughtful",
    "Timeliness",
    "Tolerance",
    "Toughness",
    "Traditional",
    "Tranquility",
    "Transparency",
    "Trust",
    "Trustworthy",
    "Truth",
    "Understanding",
    "Uniqueness",
    "Unity",
    "Valor",
    "Victory",
    "Vigor",
    "Vision",
    "Vitality",
    "Wealth",
    "Welcoming",
    "Winning",
    "Wisdom",
    "Wonder",
];

data.sentence_stems = {}

data.sentence_stems.general = [
    "I choose to ... because ...",
    "As I mature I begin to notice ...",
    "I am becoming aware ...",
    "I see ...",
    "I am a ...",
    "I like who I am because…",
    "My friends think I have an awesome…",
    "I mean a lot to…",
    "Somewhere I feel happy is…",
    "I have always wanted to…",
    "I’m secretly afraid of…",
    "This week I would enjoy doing…",
    "I often look forward to…",
    "I feel something that the future holds for me is…",
    "I get my strength from…",
    "One person couldn’t live without is…",
    "I would never…",
    "It made me feel great when…",
    "I love when…",
    "I find it hard to…",
    "My dream is to one day that…",
    "It makes me angry when…",
    "I sometimes fear that…",
    "This week is going to be…",
    "Something I deeply desire is…",
    "I flourish when…",
    "This week I hope to…",
    "Something I do secretly…",
    "I find it hard to admit…",
    "When I think of X value...",
    "When I think of a time when X value was challenged...",
    "As my understanding of X value deepens",
];

data.sentence_stems.six_pillars = [
    "Self-responsibility to me means…",
    "Independence to me means…",
    "Thinking for myself means…",
    "Trusting my own mind means…",
    "If I operate five percent more self-responsibly today…",
    "If I think for myself today…",
    "If I bring five percent more awareness to my deepest needs and wants…",
    "If I bring five percent more awareness to what I truly think and feel…",
    "I am becoming aware…",
    "If I am more straightforward about what I think and feel today…",
    "If I operate five percent more self-assertively today…",
    "If I treat my wants and needs with more respect today…",
    "If I express myself calmly and with dignity today…",
    "If I want to translate these ideas into action…",
    "If I pay more attention to my inner signals today…",
    "If I am more truthful in my dealings with people today…",
    "If I am five percent more self-accepting today…",
    "If I am self-accepting even when I make mistakes…",
    "If these ideas start working in my subconscious mind…",
    "If I disown what I am thinking and feeling…",
    "If I place other people’s thoughts above my own…",
    "When I look at what I do to impress people…",
    "If I fake who I am to make myself “likable”…",
    "I am beginning to suspect…",
    "If I am more accepting of my feelings today…",
    "If I deny and disown my feelings…",
    "If I am more accepting of my thoughts…",
    "If I deny and disown my thoughts…",
    "I am becoming aware…",
    "If I am more accepting of my fears…",
    "If I deny and disown my fears…",
    "If I were more accepting of my pain…",
    "If I deny and disown my pain…",
    "Right now it seems obvious that…",
    "If I am more accepting of my desire to be liked…",
    "If I deny and disown my desire to be liked…",
    "If I learn to manage my desire for approval…",
    "If I can acknowledge my desire for approval without being controlled by it…",
    "If I want to translate these ideas into action…",
    "If I am more accepting of my deepest self…",
    "If I deny and disown my deepest self…",
    "If I am more accepting of my intelligence…",
    "If I deny and disown my intelligence…",
    "If I allow myself to understand what I am writing…",
    "Self-responsibility means…",
    "If I am more accepting of my thoughts and feelings, whether or not anyone shares them…",
    "If I deny and disown thoughts and feelings others do not share…",
    "If I betray my thoughts and feelings in action…",
    "If I honor my thoughts and feelings in action…",
    "I am beginning to suspect…",
    "If I imagine being more self-responsible…",
    "If I imagine being more independent…",
    "If I imagine looking at things through my own eyes…",
    "If I take five percent more responsibility for the ideas I live by…",
    "If these ideas start working in my subconscious mind…",
    "If I honor my judgment today…",
    "Sometimes I keep myself passive when I…",
    "Sometimes I make myself helpless when I…",
    "If I pretend to be less than I am…",
    "If I allow myself to absorb what I am writing…",
    "If I bring five percent more integrity into my relationships…",
    "If I take five percent more responsibility for my choice of companions…",
    "If I take five percent more responsibility for my personal happiness…",
    "If I take five percent more responsibility for the level of my self-esteem…",
    "I am becoming aware…",
    "If I lived five percent more authentically today…",
    "If I treat my thoughts and feelings with respect today…",
    "If I experiment with being more self-assertive today…",
    "If I am willing to see what I see and know what I know…",
    "If I fully face the meaning of what I am writing…",
    "If I hold myself accountable for my promises and commitments…",
    "If I stop all excuse-making and alibiing…",
    "If I refuse to surrender to helplessness…",
    "If I were willing to say “yes” when I want to say “yes” and “no” when I want to say “no”…",
    "I am beginning to suspect…",
    "If I were willing to let people see who I am…",
    "If I took more responsibility for delivering on my commitments…",
    "If I operate five percent more self-responsibly at work…",
    "If I operate five percent more self-responsibly in my relationships…",
    "If I choose to translate these ideas into action…",
    "If I stay connected with what I truly think and feel…",
    "If I take more responsibility for fulfilling my wants…",
    "If I refuse to blame anyone…",
    "If I make my happiness a conscious goal…",
    "Right now it seems clear…",
    "If I look people in the eyes and tell the truth today…",
    "If I refuse to be ruled by fear of disapproval…",
    "If I refuse to hide who I am…",
    "If I am simple, honest, and straightforward today…",
    "If I allow what I am writing to fully penetrate…",
    "If I bring five percent more integrity to my relationships…",
    "If I remain loyal to the values I believe are right…",
    "If I refuse to live by values I do not respect…",
    "If I treat my self-respect as a high priority…",
    "I am becoming aware…",
    "If I accept responsibility for my life and well-being…",
    "If I accept responsibility for my choices and decisions…",
    "If I accept responsibility for my actions…",
    "If I accept responsibility for how I deal with people…",
    "If I choose to translate these ideas into action…",
    "If I want to grow in independence, I will need to…",
    "If I want to grow in self-esteem, I will need to…",
    "If I want to be more authentic, I will need to…",
    "If I want to outgrow dependency, I will need to…",
    "If I am willing to experiment with these ideas in action…",
    "If I look at things through my own eyes today…",
    "If I am willing to see what I see and know what I know…",
    "If I am truthful today, even if it’s difficult…",
    "I grow in self-respect when I…",
    "I am becoming aware…",
    "If I operate five percent more self-responsibly today…",
    "If I operate five percent more self-assertively today…",
    "If I operate five percent more authentically today…",
    "If I operate five percent more honestly today…",
    "Right now it seems clear that…",
    "As I grow in self-responsibility…",
    "As I grow in independence…",
    "As I learn to say what I truly think and feel…",
    "As I learn to look at things through my own eyes…",
    "If these ideas start working in my subconscious mind…",
    "Sometimes when I am afraid of self-responsibility I…",
    "Sometimes when I am afraid of independence I…",
    "If I want to outgrow any fear I have of self-responsibility…",
    "If I want to outgrow any fear I have of independence…",
    "I am beginning to suspect…",
    "One of the things I’ve been learning through this program is…",
    "As I notice when I am being self-responsible and when I am not fully…",
    "As I notice when I am being authentic and when I am not fully…",
    "As I notice how I feel when I am honest…",
    "I am becoming aware…",
    "I feel most proud of myself when I…",
    "I feel least proud of myself when I…",
    "If I give myself credit for my willingness to struggle…",
    "If I give myself credit for my dedication to personal growth…",
    "If I allow myself to understand what I am writing…",
    "As I learn to translate what I am learning into action…",
    "As I continue the struggle, even when it’s difficult…",
    "If I choose to persevere, no matter how long it takes…",
    "One of the ways I am changing is…",
    "I am beginning to suspect…",
    "As my understanding of self-responsibility deepens…",
    "As my understanding of independence deepens…",
    "As I learn to be more authentic when dealing with people…",
    "As everything I am learning takes root in my subconscious mind…",
    "I am becoming aware…",
    "As I learn to operate at a higher level of self-responsibility…",
    "As I learn to operate at a higher level of independence…",
    "As I learn to pay more attention to what I truly think and feel…",
    "As I learn to treat myself with more respect…",
    "As I go on translating these learnings into action…",
];

export default data;